execute pathogen#infect()
syntax on
filetype plugin indent on

"set foldmethod=indent
"set paste
set nocompatible
set bs=2
set ai
set backup
set noerrorbells
set autoindent
set autowrite
set ruler
set showmode
"set number

set history=50        " keep 50 lines of command line history
set tabstop=2
set expandtab
set shiftwidth=2
set softtabstop=2
set showmatch
set vb

"color darkblue
set showcmd        " display incomplete commands
set incsearch        " do incremental searching
" allow backspacing over everything in insert mode
set backspace=indent,eol,start
set cursorline
nmap gV `[v`]           " highlight last inserted text

"au BufRead,BufNewFile *.md set filetype=markdown

set nocompatible
filetype plugin on       " may already be in your .vimrc

let g:pencil#wrapModeDefault = 'soft'   " default is 'hard'
augroup pencil
  autocmd!
  autocmd FileType markdown,mkd call pencil#init()
  autocmd FileType text         call pencil#init()
augroup END

